use core::arch::asm;
use core::arch::global_asm;

global_asm!(include_str!("idt.S"));

pub const VECTOR_IRQ_BASE: u32 = 48;

pub fn init() {
    let idtr = Idtr {
        limit: (core::mem::size_of::<[IdtEntry; 256]>() - 1) as u16,
        base: IDT.as_ptr() as u64,
    };

    unsafe {
        asm!("lidt [{}]", in(reg) &idtr);
    }
}

#[repr(C, packed)]
struct Idtr {
    limit: u16,
    base: u64,
}

#[repr(C, packed)]
struct IdtEntry {
    offset0: u16,
    segment: u16,
    attrs: u16,
    offset1: u16,
    offset2: u32,
    reserved: u32,
}

impl IdtEntry {
    pub const fn new(handler: usize) -> Self {
        Self {
            offset0: (handler & 0xffff) as u16,
            segment: 8,    // KERNEL_CS
            attrs: 0x8e00, // Present, DPL=0, 64-bit interrupt gate, IST=0
            offset1: ((handler >> 16) & 0xffff) as u16,
            offset2: ((handler >> 32) & 0xffffffff) as u32,
            reserved: 0,
        }
    }
}
#[repr(transparent)]
struct Handler([u8; 16]);

extern "C" {
    static interrupt_handlers: [Handler; 256];
}

// TODO: Build IDT in compile time. Maybe using assembly macros?
static IDT: spin::Lazy<[IdtEntry; 256]> = spin::Lazy::new(|| {
    [
        IdtEntry::new(unsafe { &raw const interrupt_handlers[0] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[1] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[2] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[3] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[4] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[5] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[6] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[7] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[8] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[9] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[10] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[11] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[12] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[13] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[14] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[15] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[16] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[17] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[18] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[19] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[20] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[21] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[22] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[23] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[24] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[25] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[26] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[27] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[28] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[29] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[30] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[31] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[32] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[33] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[34] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[35] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[36] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[37] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[38] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[39] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[40] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[41] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[42] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[43] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[44] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[45] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[46] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[47] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[48] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[49] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[50] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[51] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[52] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[53] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[54] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[55] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[56] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[57] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[58] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[59] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[60] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[61] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[62] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[63] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[64] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[65] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[66] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[67] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[68] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[69] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[70] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[71] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[72] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[73] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[74] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[75] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[76] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[77] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[78] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[79] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[80] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[81] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[82] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[83] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[84] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[85] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[86] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[87] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[88] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[89] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[90] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[91] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[92] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[93] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[94] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[95] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[96] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[97] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[98] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[99] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[100] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[101] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[102] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[103] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[104] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[105] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[106] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[107] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[108] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[109] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[110] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[111] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[112] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[113] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[114] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[115] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[116] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[117] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[118] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[119] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[120] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[121] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[122] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[123] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[124] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[125] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[126] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[127] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[128] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[129] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[130] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[131] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[132] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[133] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[134] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[135] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[136] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[137] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[138] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[139] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[140] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[141] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[142] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[143] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[144] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[145] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[146] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[147] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[148] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[149] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[150] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[151] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[152] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[153] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[154] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[155] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[156] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[157] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[158] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[159] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[160] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[161] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[162] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[163] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[164] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[165] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[166] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[167] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[168] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[169] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[170] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[171] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[172] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[173] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[174] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[175] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[176] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[177] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[178] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[179] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[180] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[181] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[182] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[183] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[184] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[185] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[186] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[187] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[188] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[189] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[190] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[191] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[192] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[193] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[194] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[195] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[196] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[197] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[198] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[199] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[200] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[201] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[202] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[203] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[204] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[205] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[206] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[207] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[208] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[209] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[210] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[211] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[212] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[213] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[214] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[215] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[216] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[217] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[218] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[219] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[220] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[221] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[222] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[223] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[224] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[225] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[226] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[227] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[228] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[229] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[230] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[231] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[232] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[233] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[234] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[235] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[236] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[237] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[238] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[239] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[240] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[241] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[242] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[243] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[244] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[245] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[246] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[247] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[248] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[249] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[250] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[251] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[252] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[253] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[254] as usize }),
        IdtEntry::new(unsafe { &raw const interrupt_handlers[255] as usize }),
    ]
});
