[package]
name = "hello_from_javascript"
publish = false
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
starina = { workspace = true }
