[package]
name = "itest"
publish = false
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "itest"
path = "main.rs"

[dependencies]
starina = { workspace = true }
