[package]
name = "tcpip"
publish = false
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "tcpip"
path = "main.rs"

[dependencies]
starina = { workspace = true }
starina_types = { workspace = true }
