// This file is auto-generated by starina_build_sdk.
// Do not edit this file directly.
#![allow(unused)]

use serde::Deserialize;
use starina::channel::Channel;
use starina::collections::HashMap;
use starina::device_tree::DeviceTree;
use starina::prelude::*;
use starina::spec::ParsedAppSpec;
use starina::spec::ParsedDeviceMatch;
use starina::spec::ParsedEnvItem;
use starina::spec::ParsedEnvType;
use starina::spec::ParsedExportItem;
use starina::syscall::VsyscallPage;

#[derive(Debug, Deserialize)]
pub struct Env {
    pub startup_ch: Channel,
    pub device_tree: DeviceTree,
}

pub const APP_SPEC: ParsedAppSpec = ParsedAppSpec {
    name: "virtio_net",
    env: &[ParsedEnvItem {
        name: "device_tree",
        ty: ParsedEnvType::DeviceTree {
            matches: &[ParsedDeviceMatch::Compatible("virtio,mmio")],
        },
    }],
    exports: &[ParsedExportItem::Service {
        service: "device/ethernet",
    }],
    main,
};

fn main(env_json: &[u8]) {
    starina::eventloop::app_loop::<Env, crate::State, crate::App>("virtio_net", env_json);
}
