[package]
name = "boot_riscv64"
publish = false
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "boot_riscv64"
path = "main.rs"
test = false          # Because this is arch-specific.

[dependencies]
kernel = { workspace = true }
