[package]
name = "hello_wasm"
publish = false
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
starina = { workspace = true }

[build-dependencies]
wasmer = "5.0.4"
