[package]
name = "starina_kernel"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
path = "lib.rs"

[dependencies]
starina_utils = { workspace = true }
starina_types = { workspace = true }
starina_bump_allocator = { workspace = true }
starina_elf = { workspace = true }
starina_inlinedvec = { workspace = true }
hashbrown = { workspace = true }
fdt-rs = { workspace = true }

# TODO: Remove this dependency
spin = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
minijinja = { workspace = true }
starina_types = { workspace = true }
starina_autogen = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }
