// This file is auto-generated by starina_build_sdk.
// Do not edit this file directly.
#![allow(unused)]

use serde::Deserialize;
use starina::channel::Channel;
use starina::collections::HashMap;
use starina::device_tree::DeviceTree;
use starina::prelude::*;
use starina::spec::AppSpec;
use starina::spec::DeviceMatch;
use starina::spec::EnvItem;
use starina::spec::EnvType;
use starina::spec::ExportItem;
use starina::syscall::VsyscallPage;

#[derive(Debug, Deserialize)]
pub struct Env {
    pub startup_ch: Channel,
    pub driver: Channel,
}

pub const APP_SPEC: AppSpec = AppSpec {
    name: "tcpip",
    env: &[EnvItem {
        name: "driver",
        ty: EnvType::Service {
            service: "device/ethernet",
        },
    }],
    exports: &[ExportItem::Service { service: "tcpip" }],
    main,
};

fn main(env_json: &[u8]) {
    starina::eventloop::app_loop::<Env, crate::State, crate::App>("tcpip", env_json);
}
