[package]
name = "echo"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "echo"
path = "main.rs"

[dependencies]
starina_api = { workspace = true }

[build-dependencies]
starina_autogen = { workspace = true }
